font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
enable_audio_bell no
font_size 9.0
window_padding_width 4
include theme.conf
cursor_trail 1
# Hide all window decorations
#hide_window_decorations yes

#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0

# Vertical split (side-by-side)
map ctrl+shift+v launch --location=vsplit

# Horizontal split (top-bottom)
map ctrl+shift+h launch --location=hsplit

# Close current window
map ctrl+shift+q close-window

# Move between panes
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down


# initially empty, to be configured by user and remains static
include userprefs.conf

# Note: as userprefs.conf is included at the end, settings configured in this file will override the defaults
